version: '3.9'

services:
  db:
    restart: always
    container_name: pg
    image: postgres:latest
    env_file:
      - .env
    network_mode: host

  web:
    build:
      target: prod
      context: .
      dockerfile: ./Dockerfile
    image: app/app_prod
    container_name: app_fastapi
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      POSTGRES_DB: trading_platform
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    working_dir: /app/fastapi-application
    command: ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "main:main_app"]
    network_mode: host
