services:
  pg:
    image: postgres
    container_name: pg_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network

  web:
    build:
      target: dev
      context: .
      dockerfile: ./Dockerfile
    image: app/app_dev
    container_name: app_fastapi
    depends_on:
      - pg
    volumes:
      - .:/app
    working_dir: /app/products-app
    ports:
      - 8000:8000
    command: ["uvicorn", "main:main_app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - app-network

networks:
  app-network: