version: '3.9'

services:
  pg:
    image: postgres
    container_name: pg_db
    restart: always
    environment:
      POSTGRES_DB: trading
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"